### ISSUE TITLE
Adding Authentification to broker

### ISSUE THREAD

**Issue by Moooser** [hpfeeds/hpfeeds#51]
in the documentation under Authentification section following lines can be found for the docker-compose.yml file:

```
version: '2.1'

volumes:
  hpfeeds_userdb: { }
services:
  hpfeeds:
    image: hpfeeds/hpfeeds-broker
    container_name: hpfeeds
    ports:
     - "0.0.0.0:10000:10000"
    volumes:
     - hpfeeds_data:/app/var
```

when I am running 

```
sudo docker-compose up -d
```

or 

```
docker-compose run --rm hpfeeds sqlite3 sqlite.db
```

(I am not really sure, which command I am supposed to run)

following error is displayed:

ERROR: Named volume "hpfeeds_data:/app/var:rw" is used in service "hpfeeds" but no declaration was found in the volumes section.

is the content of the docker-compose.yml wrong? Unfortunately I don´t know a thing about docker or docker-compose, I just want to get hpfeeds running...

Thanks in advance

**Comment by Jc2k** [comment]
Hi @Moooser 

Thanks for raising the issue - there was a typo in the docs. The key under the `volume` section needs to match the key under the `volumes` key. I.e. both should be `hpfeeds_userdb` or both should be `hpfeeds_data`.  I've just pushed this to the docs git:

```yaml
   version: '2.1'

   volumes:
     hpfeeds_userdb: {}

   services:
     hpfeeds:
       image: hpfeeds/hpfeeds-broker
       container_name: hpfeeds
       ports:
        - "0.0.0.0:10000:10000"
       volumes:
        - hpfeeds_userdb:/app/var
```

Hopefully that should be reflected on the site shortly.

If you are wanting to run a broker in a production or production-like setting then you may want to read up on docker-compose. For example, you can set a `restart` key to control when the broker should start. By default it wouldn't restart if it crashed and it wouldn't start automatically on boot. Also there are a bunch of hardening options you might want to consider, like setting it to run as a different user or making `/` read only. But thats out of scope for us to set Docker best practice.
